-- regions dictionary
CREATE TABLE region (
    id bigint PRIMARY KEY,
    name varchar NOT NULL
);
INSERT INTO region(id, name) VALUES (52, 'Московская область');
INSERT INTO region(id, name) VALUES (182394, 'Москва город');

-- industries dictionary
CREATE TABLE industry (
    id bigint PRIMARY KEY,
    name varchar NOT NULL
);
INSERT INTO industry(id, name) VALUES (32, 'Полное строительство и реконструкция зданий и сооружений');

-- requests for parsing
CREATE TABLE request (
    region_id bigint NOT NULL,
    industry_id bigint NOT NULL,
    -- request priority level for parsing worker instances. FCFS by default
    priority bigint GENERATED BY DEFAULT AS IDENTITY,
    created_timestamp timestamp DEFAULT now() NOT NULL,

    CONSTRAINT pk_request PRIMARY KEY(region_id, industry_id),
    CONSTRAINT fk_request_region FOREIGN KEY(region_id) REFERENCES region(id),
    CONSTRAINT fk_request_industry FOREIGN KEY(industry_id) REFERENCES industry(id)
);
-- todo: following INSERT statements are for some sample data i.e. to be commented out when requests creation user interface is completed
INSERT INTO request(region_id, industry_id, priority) VALUES (182394, 32, 1);
INSERT INTO request(region_id, industry_id, priority) VALUES (52, 32, 2);

-- tenders data
CREATE TABLE tender (
    id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    -- request id (it's not just region id alone, see FK definition below)
    region_id bigint NOT NULL,
    industry_id bigint NOT NULL,
    -- tender details page link (at rostender dot info)
    tender_webpage_link character varying NOT NULL,
    -- date that tender was put to queue for getting tender details i.e. record creation date
    queued_timestamp timestamp DEFAULT now() NOT NULL,
    -- tender details below are NULL until one of worker instances has processed the details getting job
    tender_number integer,
    tender_date date,
    tender_title varchar,
    tender_location character varying,
    tender_ordering_company character varying,
    tender_amount numeric,
    tender_registration_start_timestamp timestamp,
    tender_registration_end_timestamp timestamp,
    tender_summary_date date,
    tender_status integer DEFAULT 0 NOT NULL,
    -- Links to next and previous versions ID of the same tender, for keeping all versions of updated tenders
    next_version_tender_id bigint,
    prev_version_tender_id bigint,

    CONSTRAINT fk_tender_request FOREIGN KEY(region_id, industry_id) REFERENCES request(region_id, industry_id),
    CONSTRAINT fk_tender_next_tender FOREIGN KEY(next_version_tender_id) REFERENCES tender(id),
    CONSTRAINT fk_tender_prev_tender FOREIGN KEY(prev_version_tender_id) REFERENCES tender(id)
);